"use strict";
let placesToVisit = ["Murree", "Sawat", "Tokyo", "London", "Turkey", "Hong Kong", "Germany", "U.K."];
console.log("Original Array Order:", placesToVisit);
console.log("Alphabetical Order:", [...placesToVisit].sort());
console.log("Original Array Order:", placesToVisit);
console.log("Reverse Alphabetical Order:", [...placesToVisit].sort().reverse());
console.log("Original Array Order:", placesToVisit);
console.log("Reverse Array Order:", placesToVisit.reverse());
console.log("Again Original Array Order:", placesToVisit.reverse());
console.log("Original Alphabetical Array Order:", placesToVisit.sort());
console.log("Original Reverse Alphabetical Array Order:", placesToVisit.reverse());
