"use strict";
let friendNames = ["Harry", "Bittering", "Ahmed", "Ali"];
var msg = "Hello," + friendNames[0].toLowerCase().charAt(0).toUpperCase() + friendNames[0].slice(1) + ".";
console.log(msg);
var msg = "Hello," + friendNames[1].toLowerCase().charAt(0).toUpperCase() + friendNames[1].slice(1) + ".";
console.log(msg);
var msg = "Hello," + friendNames[2].toLowerCase().charAt(0).toUpperCase() + friendNames[2].slice(1) + ".";
console.log(msg);
var msg = "Hello," + friendNames[3].toLowerCase().charAt(0).toUpperCase() + friendNames[3].slice(1) + ".";
console.log(msg);
